# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PhoenixiOS' do
    # 响应编程 另外一个是 RxSwift, ReactiveCocoa
#    pod 'RxSwift' #, '~> 5'
    pod 'RxCocoa' #, '~> 5'
    pod 'ReactiveCocoa' #, '~> 9.0'

    pod 'Alamofire' , '~> 4.9.1'
#    pod 'Kingfisher' , '~> 4.10.1'
    pod 'SnapKit' #, '~> 4.2.0'
    pod 'SwiftSoup' # html 标签解析 puppeteer
    pod 'SQLite.swift', '~> 0.12.2'
    pod 'YSToast'
end


#Installing Alamofire (4.9.1)
#Installing ReactiveCocoa (10.2.0)
#Installing ReactiveSwift (6.2.1)
#Installing RxCocoa (5.1.1)
#Installing RxRelay (5.1.1)
#Installing RxSwift (5.1.1)
#Installing SnapKit (4.2.0)
#Installing SwiftSoup (2.3.1)
